/**
 * Microsoft APM regenerates a whole AGENTS.md or CLAUDE.md when its generated
 * marker is one of the first five lines (apm-cli 0.30.0: `has_generated_marker_header`
 * in compilation/constants.py, `CLAUDE_HEADER` in compilation/claude_formatter.py).
 * A managed area agctx added to such a file would be erased by the next `apm compile`.
 */

const AGENTS_MARKERS = ['<!-- Generated by APM CLI from .apm/ primitives -->', '<!-- Generated by APM CLI from distributed .apm/ primitives -->'];
const CLAUDE_MARKERS = ['<!-- Generated by APM CLI -->'];
const HEADER_LINES = 5;

/** Whether APM in its default mode would regenerate this file over agctx's changes. */
export function apmRegenerates(relativePath: string, content: string | null): boolean {
  if (content === null) return false;
  const name = relativePath.split('/').pop();
  const markers = name === 'AGENTS.md' ? AGENTS_MARKERS : name === 'CLAUDE.md' ? CLAUDE_MARKERS : [];
  const header = new Set(content.split(/\r?\n/).slice(0, HEADER_LINES).map(line => line.trim()));
  return markers.some(marker => header.has(marker));
}
