/**
 * Microsoft APM은 생성 마커가 첫 다섯 줄 안에 있으면 AGENTS.md나 CLAUDE.md 전체를 다시 만든다
 * (apm-cli 0.30.0: compilation/constants.py의 `has_generated_marker_header`,
 * compilation/claude_formatter.py의 `CLAUDE_HEADER`). agctx가 그런 파일에 더한 관리 영역은 다음
 * `apm compile`이 지운다.
 */

const AGENTS_MARKERS = [
  '<!-- Generated by APM CLI from .apm/ primitives -->',
  '<!-- Generated by APM CLI from distributed .apm/ primitives -->'
];
const CLAUDE_MARKERS = ['<!-- Generated by APM CLI -->'];
const HEADER_LINES = 5;

/** 기본 모드의 APM이 agctx의 변경 위로 이 파일을 다시 만들지. */
export function apmRegenerates(relativePath: string, content: string | null): boolean {
  if (content === null) return false;
  const name = relativePath.split('/').pop();
  const markers = name === 'AGENTS.md' ? AGENTS_MARKERS : name === 'CLAUDE.md' ? CLAUDE_MARKERS : [];
  const header = new Set(
    content
      .split(/\r?\n/)
      .slice(0, HEADER_LINES)
      .map(line => line.trim())
  );
  return markers.some(marker => header.has(marker));
}
